---
title: "Disclaimers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Disclaimers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Clinical Context

The **sassy** system was developed in the context of, and from the perspective
of pharmaceutical clinical programming.  The examples take this perspective
into account.  Despite this context, there is nothing that limits use of the
**sassy** system to the pharmaceutical industry.  The functions are 
generalized enough that they can be used in any vertical.

### Independantly Written

Note that the **sassy** meta-package and sub-packages were written 
independently, and the authors have no association
with, approval of, or endorsement by SAS® Institute or Posit®. 

### Not for Big Data

Also note that the **sassy** family of packages is intended to be used with small and 
medium-sized data sets.  It is not recommended for big data, as big data
requires very careful control over which data is or is not loaded into memory.
That is to say, if you are dealing with more than 10 million records, 
**sassy** is not the best choice.  Suggest you investigate packages 
that were specifically designed for handling such scenarios.

